ALL: p2_1 p2_2 p2_3

p2_1:  p2_1.o
	gcc -o p2_1 p2_1.o

p2_1.o: p2_1.c
	gcc -c  p2_1.c

p2_2:  p2_2.o
	gcc -o p2_2 p2_2.o

p2_2.o: p2_2.c
	gcc -c  p2_2.c

p2_3:  p2_3.o
	gcc -o p2_3 p2_3.o

p2_3.o: p2_3.c
	gcc -c  p2_3.c
